#!/usr/bin/env bash
set -euo pipefail

# Env vars expected: REPO (e.g. "tos1111/tos"), FILE_PATH (path to analyzed file)
# Input file: raw_output.json

COMPANY=$(jq -r '.company' raw_output.json | tr -cd 'a-z0-9-')
PRODUCT=$(jq -r '.product' raw_output.json | tr -cd 'a-z0-9-')
FILENAME="${COMPANY}-${PRODUCT}-summary.md"

ENCODED_FILE=$(jq -rn --arg path "$FILE_PATH" '$path | @uri')
BASE_URL="https://github.com/${REPO}/blob/main/${ENCODED_FILE}"

MODEL="claude-sonnet-4-6"
RUN_DATE=$(date -u +"%Y-%m-%d")

echo "This is not legal advice. This is an AI summary for informational purposes only, generated by $MODEL on $RUN_DATE." > "$FILENAME"
echo "" >> "$FILENAME"

jq -c '.sections[]' raw_output.json | while IFS= read -r section; do
  SECTION_NAME=$(echo "$section" | jq -r '.sectionName')
  echo "## ${SECTION_NAME}" >> "$FILENAME"
  echo "" >> "$FILENAME"

  echo "$section" | jq -c '.categories[]' | while IFS= read -r category; do
    CATEGORY_NAME=$(echo "$category" | jq -r '.name')
    echo "### ${CATEGORY_NAME}" >> "$FILENAME"
    echo "" >> "$FILENAME"

    echo "$category" | jq -c '.items[]' | while IFS= read -r item; do
      START=$(echo "$item" | jq -r '.start')
      END=$(echo "$item" | jq -r '.end')
      QUOTE=$(echo "$item" | jq -r '.quote')
      SUMMARY_TEXT=$(echo "$item" | jq -r '.summary')
      LINK="${BASE_URL}#L${START}-L${END}"
      echo "${SUMMARY_TEXT} <sup>[${START}-${END}](${LINK} \"${QUOTE}\")</sup>" >> "$FILENAME"
      echo "" >> "$FILENAME"
    done
  done
done

echo "filename=$FILENAME" >> "$GITHUB_OUTPUT"

FIELD=$(jq -r '.secondary_field' raw_output.json)
if [ "$FIELD" != "null" ] && [ -n "$FIELD" ]; then
  echo "flag_set=true" >> "$GITHUB_OUTPUT"
  echo "notice_body<<EOF" >> "$GITHUB_OUTPUT"
  echo "$FIELD" >> "$GITHUB_OUTPUT"
  echo "EOF" >> "$GITHUB_OUTPUT"
else
  echo "flag_set=false" >> "$GITHUB_OUTPUT"
fi
